import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/?locale=es');
  await page.getByRole('link', { name: 'Iniciar sesión' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('oscarmola2015@gmail.com');
  await page.getByRole('textbox', { name: 'Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('Holaadios69');
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await page.getByRole('button', { name: 'Toggle Sidebar' }).click();
  await page.getByRole('link', { name: 'Peticiones', exact: true }).click();
  await page.getByRole('button', { name: 'Nueva Peticion' }).click();
  await page.getByRole('textbox', { name: 'Título *' }).click();
  await page.getByRole('textbox', { name: 'Título *' }).fill('Petici');
  await page.getByRole('textbox', { name: 'Título *' }).press('Dead');
  await page.getByRole('textbox', { name: 'Título *' }).fill('Petición para creaci');
  await page.getByRole('textbox', { name: 'Título *' }).press('Dead');
  await page.getByRole('textbox', { name: 'Título *' }).fill('Petición para creación de Cubos de Palomitas personalizados');
  await page.getByRole('textbox', { name: 'Descripción *' }).click();
  await page.getByRole('textbox', { name: 'Descripción *' }).fill('Una aplicaci');
  await page.getByRole('textbox', { name: 'Descripción *' }).press('Dead');
  await page.getByRole('textbox', { name: 'Descripción *' }).fill('Una aplicación que te deje modificar tus cubos de palomitas para adecuarlo a tus gustos para tener cubos tem');
  await page.getByRole('textbox', { name: 'Descripción *' }).press('Dead');
  await page.getByRole('textbox', { name: 'Descripción *' }).fill('Una aplicación que te deje modificar tus cubos de palomitas para adecuarlo a tus gustos para tener cubos temáticos');
  await page.getByRole('spinbutton', { name: 'Objetivo numérico *' }).click();
  await page.getByRole('spinbutton', { name: 'Objetivo numérico *' }).click();
  await page.getByRole('spinbutton', { name: 'Objetivo numérico *' }).fill('30');
  await page.getByRole('combobox', { name: 'Foro asociado *' }).click();
  await page.getByRole('option', { name: 'TechNova Hub' }).click();
  await page.getByRole('switch', { name: 'Permitir comentarios *' }).click();
  await page.getByPlaceholder('Selecciona los tags para la').click();
  await page.getByRole('option', { name: 'Alimentos' }).click();
  await page.getByRole('option', { name: 'Accesorios' }).click();
  await page.getByRole('option', { name: 'Edición Limitada' }).click();
  await page.getByRole('option', { name: 'Novedad' }).click();
  await page.getByRole('button', { name: 'Clear all' }).click();
  await page.getByRole('button', { name: 'Arrastra y suelta tus imá' }).click();
  await page.locator('body').setInputFiles('0202746_depo17862-cubo-palomitas-25u-3900ml.jpeg');
  await page.getByRole('button', { name: 'Arrastra y suelta tus imá' }).click();
  await page.locator('body').setInputFiles('images.jpeg');
  await page.getByRole('button', { name: 'Crear Petición' }).click();
  await page.getByRole('img', { name: 'Petición para creación de Cubos de Palomitas personalizados - imagen 1' }).click();
  await page.getByRole('button', { name: 'Next slide' }).click();
  await page.locator('.data-\\[state\\=open\\]\\:animate-in').first().click();
  await page.getByRole('textbox', { name: 'Escribe un comentario...' }).click();
  await page.getByRole('textbox', { name: 'Escribe un comentario...' }).fill('Yo lo veo bien');
  await page.getByRole('button', { name: 'Publicar' }).click();
  await page.getByRole('button', { name: 'Suscribirme' }).click();
  await page.getByRole('button', { name: 'Toggle Sidebar' }).click();
  await page.getByRole('link', { name: 'Peticiones' }).click();
  await page.getByRole('button', { name: 'Toggle Sidebar' }).click();
  await page.getByRole('link', { name: 'Productos', exact: true }).click();
  await page.getByRole('link').filter({ hasText: 'Healthy Bites CateringSmoothie Detox Green PowerBebida de 500ml a base de' }).click();
  await page.getByRole('button').nth(5).click();
  await page.getByRole('button', { name: '2' }).click();
  await page.getByRole('button', { name: 'Crear reseña' }).click();
  await page.getByRole('button').nth(1).click();
  await page.getByRole('textbox', { name: 'Título *' }).click();
  await page.getByRole('textbox', { name: 'Título *' }).fill('No me gust');
  await page.getByRole('textbox', { name: 'Título *' }).press('Dead');
  await page.getByRole('textbox', { name: 'Título *' }).fill('No me gustó');
  await page.getByRole('textbox', { name: 'Contenido *' }).click();
  await page.getByRole('textbox', { name: 'Contenido *' }).fill('No s');
  await page.getByRole('textbox', { name: 'Contenido *' }).press('Dead');
  await page.getByRole('textbox', { name: 'Contenido *' }).fill('No sé es como muy verde');
  await page.getByRole('button', { name: 'Crear' }).click();
  await page.locator('div').filter({ hasText: /^0$/ }).nth(1).click();
  await page.getByRole('button', { name: 'Ver perfil de empresa' }).click();
  await page.getByRole('link', { name: 'Volver a inicio' }).click();
  await page.getByText('Deal&BuyIr al inicioApuntado.').click();
  await page.getByRole('button', { name: 'Ir al inicio' }).click();
  await page.locator('.flex.flex-col.items-baseline.gap-8.w-\\[36\\%\\].mr-12 > article > .p-5 > .flex.items-center.justify-between.pt-2 > .peer').first().click();
  await page.getByRole('button', { name: 'Confirmar suscripción' }).click();
  await page.getByRole('searchbox', { name: 'Buscar...' }).click();
  await page.getByRole('searchbox', { name: 'Buscar...' }).fill('hola');
  await page.getByRole('link', { name: 'hola adios hola adios oscarnoempresa' }).click();
  await page.getByRole('button', { name: 'Mis suscripciones' }).click();
  await page.getByRole('button', { name: 'Mostrar más' }).first().click();
  await page.getByRole('button', { name: 'Mis publicaciones' }).click();
  await page.getByRole('button', { name: 'Editar perfil' }).click();
  await page.getByRole('button', { name: 'Registrar Empresa' }).click();
  await page.getByRole('textbox', { name: 'Nombre de la empresa *' }).click();
  await page.getByRole('textbox', { name: 'Nombre de la empresa *' }).fill('empresaPrueba');
  await page.getByRole('textbox', { name: 'Descripción *' }).click();
  await page.getByRole('textbox', { name: 'Descripción *' }).fill('Empresa para hacer pruebas de test');
  await page.getByRole('textbox', { name: 'Nombre de la empresa *' }).click();
  await page.getByRole('textbox', { name: 'Nombre de la empresa *' }).fill('empresaPrueba1');
  await page.getByRole('button', { name: 'Crear Empresa' }).click();
  await page.getByRole('link', { name: 'Deal&Buy.' }).click();
  await page.getByRole('button', { name: 'Cerrar sesión' }).click();
});